// Curated Spanish names for the movements EnfermiCambio recommends first.
// Canonical IDs remain unchanged, so plans and workout history stay compatible
// with the complete 1,324-exercise catalogue while this pack grows safely.
export default {
  '0025': 'press de banca con barra',
  '0047': 'press inclinado con barra',
  '0426': 'press de hombros de pie con mancuernas',
  '0334': 'elevación lateral con mancuernas',
  '0241': 'extensión de tríceps en polea con barra V',
  '0251': 'fondos de pecho',
  '2330': 'jalón al pecho en polea',
  '0027': 'remo inclinado con barra',
  '1323': 'remo sentado con cuerda',
  '0031': 'curl de bíceps con barra',
  '0313': 'curl martillo con mancuernas',
  '0043': 'sentadilla profunda con barra',
  '0085': 'peso muerto rumano con barra',
  '0739': 'prensa de piernas a 45 grados',
  '0585': 'extensión de piernas en máquina',
  '0586': 'curl femoral tumbado en máquina',
  '0605': 'elevación de pantorrillas de pie en máquina',
  '0652': 'dominadas',
  '0662': 'flexiones de brazos',
  '0685': 'carrera',
  '0549': 'balanceo con kettlebell',
  '0534': 'sentadilla goblet con kettlebell',
  '0290': 'press de hombros sentado con mancuernas',
  '0289': 'press de banca con mancuernas',
  '0293': 'remo inclinado con mancuernas',
  '0336': 'zancadas con mancuernas',
  '0300': 'peso muerto con mancuernas',
  '0687': 'giro ruso',
  '0274': 'abdominal en el suelo',
  '0630': 'escalador',
  '0705': 'plancha lateral',
}
